### ISSUE TITLE
Debug Arduino code returning an error after consecutive moves

### ISSUE THREAD

**Issue by nashirj** [ucfai/knightros-gambit#261]
Input:
```
% Move chess piece from b1 to c3 
~0EGII1

% Move from piece from f7 to f5
~0QOMO0
```

Output:
```
Welcome to Knightro's Gambit
Note: When sending debug messages to board or using a test file that is comprised of `Message` type messages, updating and maintaining game state is not supported.
It is required that all messages in a .txt testfile are valid.

RUNNING IN TEST MODE...

r n b q k b n r 8
p p p p p p p p 7
. . . . . . . . 6
. . . . . . . . 5
. . . . . . . . 4
. . . . . . . . 3
P P P P P P P P 2
R N B Q K B N R 1
a b c d e f g h 

Board Status: IDLE

Board Status: IDLE
Sending message "~0EGII0" to arduino

Board Status: IDLE
Sending message "~0EGII0" to arduino
Received message: ~100

Board Status: EXECUTING_MOVE
Received message: ~000

Board Status: IDLE
Removed message from queue

Board Status: IDLE

Board Status: IDLE
Sending message "~0QOMO1" to arduino

Board Status: IDLE
Sending message "~0QOMO1" to arduino
Received message: ~101

Board Status: EXECUTING_MOVE
Received message: ~321

Board Status: ERROR
Traceback (most recent call last):
  File "/home/knightr0/knightros-gambit/firmware/raspi/cliinterface.py", line 149, in <module>
    main()
  File "/home/knightr0/knightros-gambit/firmware/raspi/cliinterface.py", line 113, in main
    made_move = game.process(players[current_player])
  File "/home/knightr0/knightros-gambit/firmware/raspi/game.py", line 104, in process
    raise ValueError("Unimplemented, need to handle errors")
ValueError: Unimplemented, need to handle errors
```

**Comment by nashirj** [comment]
"~321" corresponds to a movement error, so something is going on in the Arduino code.
